import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1")
DEFAULT_MODEL = os.getenv("DEFAULT_MODEL", "qwen3.5-plus")

TECH_AGENT_TEMPERATURE = 0.7
PRESSURE_AGENT_TEMPERATURE = 0.7
COMPREHENSIVE_AGENT_TEMPERATURE = 0.8
EVALUATOR_TEMPERATURE = 0.3
RESUME_PARSER_TEMPERATURE = 0.1
